{"id":"node_modules/exception-factory/src/exceptionFactory.js","dependencies":[{"name":"/mnt/f/programming/vue/vh/package.json","includedInParent":true,"mtime":1551045322903},{"name":"/mnt/f/programming/vue/vh/.babelrc","includedInParent":true,"mtime":1551042313446},{"name":"/mnt/f/programming/vue/vh/node_modules/exception-factory/package.json","includedInParent":true,"mtime":1551045323082}],"generated":{"js":"var exceptionFactory = {};\nexceptionFactory.build = function (name) {\n\t/*\n\t * PREFIX MESSAGE\n\t */\n\tvar prefixMessage = arguments[1] || '';\n\t/*\n\t * CONSTRUCTOR OF NEW EXCEPTION\n\t */\n\tvar newException = function() {\n\t\t/*\n\t\t * SET ARGS\n\t\t */\n\t\tvar $args = Array.prototype.slice.call(arguments);\n\t\t/*\n\t\t * SET ERROR ARGS\n\t\t */\n\t\tvar $errorArgs = $args.slice(2);\n\t\t$errorArgs.unshift($args[0]);\n\t\t/*\n\t\t * CREATE ERROR OBJECT\n\t\t */\n\t\tvar $error = Error.apply(this, $errorArgs);\n \t\tthis.name = $error.name = name;\n\t\tthis.code = $args[1] !== undefined ? $args[1] : 0;\n\t\tthis.stack = $error.stack;\n\t\tthis.message = prefixMessage + $error.message;\n\t};\n\t/*\n\t * NAME OF NEW EXCEPTION\n\t */\n\tnewException.name = newException.$name = name;\n\t/*\n\t * PROTOTYPE OF NEW EXCEPTION\n\t */\n\tnewException.prototype = Object.create(Error.prototype, {\n\t\tconstructor: {\n\t\t\tvalue: newException,\n\t\t\twritable: true,\n\t\t\tconfigurable: true\n\t\t}\n\t});\n\t/*\n\t * SET CONST OF NEW EXCEPTION\n\t */\n\tvar $const = {};\n\tnewException.const = function(key, value) {\n\t\tif (arguments.length === 0)\n\t\t\treturn $const;\n\t\telse {\n\t\t\tif ($const[key] !== undefined)\n\t\t\t\tthrow new Error(key + ' const is already defined for ' + name + ' exception');\n\t\t\tif (newException[key] !== undefined)\n\t\t\t\tthrow new Error(key + ' value is reserved on ' + name + ' exception');\n\t\t\tObject.defineProperty(newException, key, {\n\t\t\t\t__proto__: null,\n\t\t\t\tenumerable: true,\n\t\t\t\tvalue: value,\n\t\t\t});\n\t\t}\n\t\treturn newException;\n\t};\n\treturn newException;\n}\n\nmodule.exports = exceptionFactory;","map":{"mappings":[{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":1,"column":0},"generated":{"line":1,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":2,"column":0},"generated":{"line":2,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":3,"column":0},"generated":{"line":3,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":4,"column":0},"generated":{"line":4,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":5,"column":0},"generated":{"line":5,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":6,"column":0},"generated":{"line":6,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":7,"column":0},"generated":{"line":7,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":8,"column":0},"generated":{"line":8,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":9,"column":0},"generated":{"line":9,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":10,"column":0},"generated":{"line":10,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":11,"column":0},"generated":{"line":11,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":12,"column":0},"generated":{"line":12,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":13,"column":0},"generated":{"line":13,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":14,"column":0},"generated":{"line":14,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":15,"column":0},"generated":{"line":15,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":16,"column":0},"generated":{"line":16,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":17,"column":0},"generated":{"line":17,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":18,"column":0},"generated":{"line":18,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":19,"column":0},"generated":{"line":19,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":20,"column":0},"generated":{"line":20,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":21,"column":0},"generated":{"line":21,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":22,"column":0},"generated":{"line":22,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":23,"column":0},"generated":{"line":23,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":24,"column":0},"generated":{"line":24,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":25,"column":0},"generated":{"line":25,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":26,"column":0},"generated":{"line":26,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":27,"column":0},"generated":{"line":27,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":28,"column":0},"generated":{"line":28,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":29,"column":0},"generated":{"line":29,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":30,"column":0},"generated":{"line":30,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":31,"column":0},"generated":{"line":31,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":32,"column":0},"generated":{"line":32,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":33,"column":0},"generated":{"line":33,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":34,"column":0},"generated":{"line":34,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":35,"column":0},"generated":{"line":35,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":36,"column":0},"generated":{"line":36,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":37,"column":0},"generated":{"line":37,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":38,"column":0},"generated":{"line":38,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":39,"column":0},"generated":{"line":39,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":40,"column":0},"generated":{"line":40,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":41,"column":0},"generated":{"line":41,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":42,"column":0},"generated":{"line":42,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":43,"column":0},"generated":{"line":43,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":44,"column":0},"generated":{"line":44,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":45,"column":0},"generated":{"line":45,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":46,"column":0},"generated":{"line":46,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":47,"column":0},"generated":{"line":47,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":48,"column":0},"generated":{"line":48,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":49,"column":0},"generated":{"line":49,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":50,"column":0},"generated":{"line":50,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":51,"column":0},"generated":{"line":51,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":52,"column":0},"generated":{"line":52,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":53,"column":0},"generated":{"line":53,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":54,"column":0},"generated":{"line":54,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":55,"column":0},"generated":{"line":55,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":56,"column":0},"generated":{"line":56,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":57,"column":0},"generated":{"line":57,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":58,"column":0},"generated":{"line":58,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":59,"column":0},"generated":{"line":59,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":60,"column":0},"generated":{"line":60,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":61,"column":0},"generated":{"line":61,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":62,"column":0},"generated":{"line":62,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":63,"column":0},"generated":{"line":63,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":64,"column":0},"generated":{"line":64,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":65,"column":0},"generated":{"line":65,"column":0}},{"source":"node_modules/exception-factory/src/exceptionFactory.js","original":{"line":66,"column":0},"generated":{"line":66,"column":0}}],"sources":{"node_modules/exception-factory/src/exceptionFactory.js":"var exceptionFactory = {};\nexceptionFactory.build = function (name) {\n\t/*\n\t * PREFIX MESSAGE\n\t */\n\tvar prefixMessage = arguments[1] || '';\n\t/*\n\t * CONSTRUCTOR OF NEW EXCEPTION\n\t */\n\tvar newException = function() {\n\t\t/*\n\t\t * SET ARGS\n\t\t */\n\t\tvar $args = Array.prototype.slice.call(arguments);\n\t\t/*\n\t\t * SET ERROR ARGS\n\t\t */\n\t\tvar $errorArgs = $args.slice(2);\n\t\t$errorArgs.unshift($args[0]);\n\t\t/*\n\t\t * CREATE ERROR OBJECT\n\t\t */\n\t\tvar $error = Error.apply(this, $errorArgs);\n \t\tthis.name = $error.name = name;\n\t\tthis.code = $args[1] !== undefined ? $args[1] : 0;\n\t\tthis.stack = $error.stack;\n\t\tthis.message = prefixMessage + $error.message;\n\t};\n\t/*\n\t * NAME OF NEW EXCEPTION\n\t */\n\tnewException.name = newException.$name = name;\n\t/*\n\t * PROTOTYPE OF NEW EXCEPTION\n\t */\n\tnewException.prototype = Object.create(Error.prototype, {\n\t\tconstructor: {\n\t\t\tvalue: newException,\n\t\t\twritable: true,\n\t\t\tconfigurable: true\n\t\t}\n\t});\n\t/*\n\t * SET CONST OF NEW EXCEPTION\n\t */\n\tvar $const = {};\n\tnewException.const = function(key, value) {\n\t\tif (arguments.length === 0)\n\t\t\treturn $const;\n\t\telse {\n\t\t\tif ($const[key] !== undefined)\n\t\t\t\tthrow new Error(key + ' const is already defined for ' + name + ' exception');\n\t\t\tif (newException[key] !== undefined)\n\t\t\t\tthrow new Error(key + ' value is reserved on ' + name + ' exception');\n\t\t\tObject.defineProperty(newException, key, {\n\t\t\t\t__proto__: null,\n\t\t\t\tenumerable: true,\n\t\t\t\tvalue: value,\n\t\t\t});\n\t\t}\n\t\treturn newException;\n\t};\n\treturn newException;\n}\n\nmodule.exports = exceptionFactory;"},"lineCount":66}},"hash":"b2fa9cd661761598be727d60b78efc35","cacheData":{"env":{}}}